package frc.controls;

public enum ButtonCode {
	A, //1, trigger
	B, //2, yellow/black button
	X, //3, side button
	Y, //4, black button on joystick
	LEFTBUMPER,
	RIGHTBUMPER,
	BACK,
	START,
	LEFTSTICK,
	RIGHTSTICK,
	ELEVATOROVERRIDERETRACT,
	ELEVATOROVERRIDEEXTEND,
	ELEVATORDOUBLEOVERRIDERETRACT,
	ELEVATORDOUBLEOVERRIDEEXTEND,
	ARMOVERRIDERETRACT,
	ARMOVERRIDEEXTEND,
	ARMDOUBLEOVERRIDERETRACT,
	ARMDOUBLEOVERRIDEEXTEND,
	INTAKEOVERRIDERETRACT,
	CLIMBEROVERRIDERETRACT,
	CLIMBEROVERRIDEEXTEND,
	CARGOSHIP,
	ROCKETHIGH,
	ROCKETMID,
	ROCKETLOW,
	HATCHOVERRIDE,
	CARGOOVERRIDE,
	RETRACTALL,
	READYTOCOLLECT,
	CARGOHPS
}
