package frc.controls;

public enum ButtonCode {
	A, //1, trigger
	B, //2, yellow/black button
	X, //3, side button
	Y, //4, black button on joystick
	LEFTBUMPER,
	RIGHTBUMPER,
	BACK,
	START,
	LEFTSTICK,
	RIGHTSTICK,
	SETCLIMBERTOPOSITION,
	SETCLIMBERTORETRACTED,
	SETSHOTINITIATIONLINE,
	SETSHOTCONTROLPANEL,
	SHOOTERREV,
	READYTOSHOOT,
	OVERRIDEREVERSECONVEYANCE,
	OVERRIDECLIMBEXTEND,
	OVERRIDECLIMBRETRACT,
	HOPPERAGITATE,
	CONVEYANCESHOOT,
	SHOOTING_MODE_OVERRIDE,
	CLIMB_ENABLE_1,
	CLIMB_ENABLE_2,
	SHOOTFURTHER
}
